/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as SprintSprintIdRouteImport } from './routes/sprint.$sprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintSprintIdRoute = SprintSprintIdRouteImport.update({
  id: '/sprint/$sprintId',
  path: '/sprint/$sprintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/sprint/$sprintId': typeof SprintSprintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/sprint/$sprintId': typeof SprintSprintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/sprint/$sprintId': typeof SprintSprintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/team' | '/api/chat' | '/sprint/$sprintId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team' | '/api/chat' | '/sprint/$sprintId'
  id: '__root__' | '/' | '/team' | '/api/chat' | '/sprint/$sprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamRoute: typeof TeamRoute
  ApiChatRoute: typeof ApiChatRoute
  SprintSprintIdRoute: typeof SprintSprintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint/$sprintId': {
      id: '/sprint/$sprintId'
      path: '/sprint/$sprintId'
      fullPath: '/sprint/$sprintId'
      preLoaderRoute: typeof SprintSprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamRoute: TeamRoute,
  ApiChatRoute: ApiChatRoute,
  SprintSprintIdRoute: SprintSprintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
