/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SprintSprintIdRouteImport } from './routes/sprint.$sprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintSprintIdRoute = SprintSprintIdRouteImport.update({
  id: '/sprint/$sprintId',
  path: '/sprint/$sprintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteImport
  '/team': typeof TeamRouteImport
  '/login': typeof LoginRouteImport
  '/share/$shareId': typeof ShareShareIdRouteImport
  '/api/chat': typeof ApiChatRouteImport
  '/api/auth/$': typeof ApiAuthSplatRouteImport
  '/sprint/$sprintId': typeof SprintSprintIdRouteImport
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteImport
  '/team': typeof TeamRouteImport
  '/login': typeof LoginRouteImport
  '/share/$shareId': typeof ShareShareIdRouteImport
  '/api/chat': typeof ApiChatRouteImport
  '/api/auth/$': typeof ApiAuthSplatRouteImport
  '/sprint/$sprintId': typeof SprintSprintIdRouteImport
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteImport
  '/team': typeof TeamRouteImport
  '/login': typeof LoginRouteImport
  '/share/$shareId': typeof ShareShareIdRouteImport
  '/api/chat': typeof ApiChatRouteImport
  '/api/auth/$': typeof ApiAuthSplatRouteImport
  '/sprint/$sprintId': typeof SprintSprintIdRouteImport
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/team'
    | '/login'
    | '/share/$shareId'
    | '/api/chat'
    | '/api/auth/$'
    | '/sprint/$sprintId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/team'
    | '/login'
    | '/share/$shareId'
    | '/api/chat'
    | '/api/auth/$'
    | '/sprint/$sprintId'
  id:
    | '__root__'
    | '/'
    | '/team'
    | '/login'
    | '/share/$shareId'
    | '/api/chat'
    | '/api/auth/$'
    | '/sprint/$sprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamRoute: typeof TeamRoute
  LoginRoute: typeof LoginRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SprintSprintIdRoute: typeof SprintSprintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint/$sprintId': {
      id: '/sprint/$sprintId'
      path: '/sprint/$sprintId'
      fullPath: '/sprint/$sprintId'
      preLoaderRoute: typeof SprintSprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamRoute: TeamRoute,
  LoginRoute: LoginRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SprintSprintIdRoute: SprintSprintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
